const books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic fiction",
    description:
      "A classic American novel set in the glittering Jazz Age, where mysterious wealth, restless ambition, and a lost love collide on Long Island.",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg",
    price: 10.99,
  },
  {
    id: 2,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    description:
      "A witty romance about manners, family, and first impressions, following Elizabeth Bennet as she learns to look beyond pride and social expectations.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    price: 12.49,
  },
  {
    id: 3,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Historical fiction",
    description:
      "A coming-of-age story about justice and compassion in the American South, seen through a young girl's changing understanding of prejudice and courage.",
    image: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
    price: 14.99,
  },
  {
    id: 4,
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian fiction",
    description:
      "A chilling dystopian warning about surveillance, propaganda, and totalitarian power, following one man's dangerous attempt to preserve his private thoughts.",
    image: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    price: 11.75,
  },
  {
    id: 5,
    title: "Jane Eyre",
    author: "Charlotte Bronte",
    genre: "Gothic romance",
    description:
      "An independent young woman searches for love, identity, and belonging while facing hardship, moral choices, and the demands of an unforgiving society.",
    image: "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg",
    price: 9.99,
  },
  {
    id: 6,
    title: "Moby-Dick",
    author: "Herman Melville",
    genre: "Adventure",
    description:
      "A young sailor joins Captain Ahab on an obsessive hunt for a great white whale, encountering danger, wonder, and the unpredictable force of the sea.",
    image: "https://covers.openlibrary.org/b/isbn/9780142437247-L.jpg",
    price: 16.25,
  },
  {
    id: 7,
    title: "The Catcher in the Rye",
    author: "J. D. Salinger",
    genre: "Coming-of-age fiction",
    description:
      "A troubled teenager wanders New York after leaving school, wrestling with loneliness, adulthood, and his desperate search for something genuine.",
    image: "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
    price: 13.5,
  },
  {
    id: 8,
    title: "Wuthering Heights",
    author: "Emily Bronte",
    genre: "Gothic fiction",
    description:
      "A passionate and haunting tale of love, revenge, and the Yorkshire moors, where generations remain shaped by one fierce and destructive attachment.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg",
    price: 10.25,
  },
  {
    id: 9,
    title: "The Odyssey",
    author: "Homer",
    genre: "Epic poetry",
    description:
      "Odysseus faces monsters, gods, storms, and temptations during a long journey home, while his family waits through years of uncertainty.",
    image: "https://covers.openlibrary.org/b/isbn/9780140268867-L.jpg",
    price: 15.99,
  },
  {
    id: 10,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    genre: "Gothic fiction",
    description:
      "A beautiful young man trades his conscience for eternal youth, allowing a hidden portrait to bear the marks of his vanity, cruelty, and corruption.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439570-L.jpg",
    price: 8.75,
  },
  {
    id: 11,
    title: "Little Women",
    author: "Louisa May Alcott",
    genre: "Family fiction",
    description:
      "Four sisters grow up, find their voices, and build independent lives during the Civil War era while holding together a warm and imperfect family.",
    image: "https://covers.openlibrary.org/b/isbn/9780147514011-L.jpg",
    price: 12.0,
  },
  {
    id: 12,
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    genre: "Adventure",
    description:
      "A wrongfully imprisoned sailor escapes with a hidden fortune and returns under a new identity to carry out an elaborate plan for justice and revenge.",
    image: "https://covers.openlibrary.org/b/isbn/9780140449266-L.jpg",
    price: 18.49,
  },
  {
    id: 13,
    title: "Frankenstein",
    author: "Mary Shelley",
    genre: "Gothic horror",
    description:
      "A young scientist creates life and then confronts the consequences of abandoning his creation, raising questions about ambition, responsibility, and isolation.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439471-L.jpg",
    price: 10.5,
  },
  {
    id: 14,
    title: "The Adventures of Huckleberry Finn",
    author: "Mark Twain",
    genre: "Adventure",
    description:
      "A boy and an escaped man travel down the Mississippi River seeking freedom, encountering danger, hypocrisy, and difficult choices along the way.",
    image: "https://covers.openlibrary.org/b/isbn/9780142437179-L.jpg",
    price: 13.25,
  },
  {
    id: 15,
    title: "The Grapes of Wrath",
    author: "John Steinbeck",
    genre: "Historical fiction",
    description:
      "A family travels west during the Great Depression in search of work and a better life, facing poverty, injustice, and the strength of shared survival.",
    image: "https://covers.openlibrary.org/b/isbn/9780143039433-L.jpg",
    price: 17.99,
  },
  {
    id: 16,
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    genre: "Children's fiction",
    description:
      "Three lonely children restore a hidden garden and discover how friendship, fresh air, and care can transform a neglected place and their own lives.",
    image: "https://covers.openlibrary.org/b/isbn/9780064401883-L.jpg",
    price: 9.5,
  },
  {
    id: 17,
    title: "Dracula",
    author: "Bram Stoker",
    genre: "Gothic horror",
    description:
      "A group of friends confronts an ancient vampire and his growing influence, joining forces across countries and personal fears to protect those they love.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439846-L.jpg",
    price: 14.25,
  },
  {
    id: 18,
    title: "The Scarlet Letter",
    author: "Nathaniel Hawthorne",
    genre: "Historical fiction",
    description:
      "A woman faces public judgment in a strict Puritan community and gradually finds strength, dignity, and independence in the life she is forced to build.",
    image: "https://covers.openlibrary.org/b/isbn/9780142437261-L.jpg",
    price: 11.49,
  },
  {
    id: 19,
    title: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    genre: "Literary fiction",
    description:
      "An aging fisherman battles the sea in a spare story of courage and endurance, testing the limits of pride, resilience, and respect for nature.",
    image: "https://covers.openlibrary.org/b/isbn/9780684801223-L.jpg",
    price: 7.99,
  },
  {
    id: 20,
    title: "The Iliad",
    author: "Homer",
    genre: "Epic poetry",
    description:
      "Heroes and gods clash during the final days of the Trojan War, as honor, rage, loyalty, and grief shape the fate of armies and families.",
    image: "https://covers.openlibrary.org/b/isbn/9780140275360-L.jpg",
    price: 16.75,
  },
  {
    id: 21,
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    genre: "Historical fiction",
    description:
      "Love and sacrifice unfold between London and Paris during the French Revolution, as ordinary people are swept into a world of political violence and moral courage.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439600-L.jpg",
    price: 13.99,
  },
  {
    id: 22,
    title: "The Hobbit",
    author: "J. R. R. Tolkien",
    genre: "Fantasy",
    description:
      "A reluctant hobbit leaves his quiet home to join a dangerous quest, discovering courage, friendship, and a wider world filled with dragons and treasure.",
    image: "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
    price: 14.99,
  },
  {
    id: 23,
    title: "The Fellowship of the Ring",
    author: "J. R. R. Tolkien",
    genre: "Fantasy",
    description:
      "A small group begins an immense journey to destroy a powerful ring, crossing wild lands while facing ancient enemies and the burden of impossible choices.",
    image: "https://covers.openlibrary.org/b/isbn/9780544003415-L.jpg",
    price: 16.49,
  },
  {
    id: 24,
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Philosophical fiction",
    description:
      "A young shepherd follows a recurring dream across unfamiliar lands and learns to recognize opportunity, purpose, and the value of pursuing a personal calling.",
    image: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
    price: 12.99,
  },
  {
    id: 25,
    title: "The Little Prince",
    author: "Antoine de Saint-Exupery",
    genre: "Children's fiction",
    description:
      "A stranded pilot meets a thoughtful traveler from a tiny asteroid, whose stories offer a tender reflection on friendship, love, and seeing beyond appearances.",
    image: "https://covers.openlibrary.org/b/isbn/9780156012195-L.jpg",
    price: 9.99,
  },
  {
    id: 26,
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    genre: "Historical fiction",
    description:
      "A man looks back on a childhood betrayal in Afghanistan and returns to confront the past, seeking redemption amid family secrets and political upheaval.",
    image: "https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg",
    price: 15.25,
  },
  {
    id: 27,
    title: "The Book Thief",
    author: "Markus Zusak",
    genre: "Historical fiction",
    description:
      "A young girl finds comfort in stolen books and human connection while growing up in Nazi Germany, where ordinary acts of kindness carry extraordinary risks.",
    image: "https://covers.openlibrary.org/b/isbn/9780375842207-L.jpg",
    price: 14.5,
  },
  {
    id: 28,
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    genre: "Dystopian fiction",
    description:
      "In a theocratic society that controls women's bodies and identities, one handmaid quietly preserves her memories and searches for a path toward freedom.",
    image: "https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg",
    price: 13.75,
  },
  {
    id: 29,
    title: "The Metamorphosis",
    author: "Franz Kafka",
    genre: "Classic fiction",
    description:
      "After waking in a transformed body, a traveling salesman becomes isolated from his family in a strange and unsettling examination of work, duty, and identity.",
    image: "https://covers.openlibrary.org/b/isbn/9780553213690-L.jpg",
    price: 8.99,
  },
  {
    id: 30,
    title: "The Sun Also Rises",
    author: "Ernest Hemingway",
    genre: "Literary fiction",
    description:
      "A group of expatriates travels from Paris to Spain, navigating friendship, desire, disappointment, and the search for meaning after the First World War.",
    image: "https://covers.openlibrary.org/b/isbn/9780743297332-L.jpg",
    price: 11.99,
  },
  {
    id: 31,
    title: "The Call of the Wild",
    author: "Jack London",
    genre: "Adventure",
    description:
      "A domesticated dog is forced into the harsh Yukon and gradually awakens to the instincts, strength, and independence demanded by the wilderness.",
    image: "https://covers.openlibrary.org/b/isbn/9780451530417-L.jpg",
    price: 9.49,
  },
  {
    id: 32,
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    genre: "Classic fiction",
    description: "An imaginative gentleman becomes a wandering knight, turning ordinary landscapes and people into grand adventures shaped by his ideals.",
    image: "https://covers.openlibrary.org/b/isbn/9780060934347-L.jpg",
    price: 14.25,
  },
  {
    id: 33,
    title: "Les Miserables",
    author: "Victor Hugo",
    genre: "Historical fiction",
    description: "An expansive story of injustice, redemption, and sacrifice set against the social upheaval of nineteenth-century France.",
    image: "https://covers.openlibrary.org/b/isbn/9780451419439-L.jpg",
    price: 17.99,
  },
  {
    id: 34,
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    genre: "Classic fiction",
    description: "A woman challenges the expectations of Russian society while several families search for love, loyalty, and a meaningful life.",
    image: "https://covers.openlibrary.org/b/isbn/9780143035008-L.jpg",
    price: 15.49,
  },
  {
    id: 35,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    genre: "Psychological fiction",
    description: "A troubled student commits a terrible act and struggles with guilt, isolation, and the possibility of moral transformation.",
    image: "https://covers.openlibrary.org/b/isbn/9780486415871-L.jpg",
    price: 10.99,
  },
  {
    id: 36,
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    genre: "Philosophical fiction",
    description: "A turbulent family drama explores faith, freedom, responsibility, and the consequences of resentment between three very different brothers.",
    image: "https://covers.openlibrary.org/b/isbn/9780374528379-L.jpg",
    price: 16.99,
  },
  {
    id: 37,
    title: "The Master and Margarita",
    author: "Mikhail Bulgakov",
    genre: "Magical realism",
    description: "A mysterious visitor arrives in Moscow, blending satire, fantasy, romance, and questions about truth in a world turned upside down.",
    image: "https://covers.openlibrary.org/b/isbn/9780679760801-L.jpg",
    price: 13.49,
  },
  {
    id: 38,
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    genre: "Magical realism",
    description: "Several generations of one family experience love, ambition, war, and recurring patterns in the isolated town of Macondo.",
    image: "https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg",
    price: 15.99,
  },
  {
    id: 39,
    title: "The Stranger",
    author: "Albert Camus",
    genre: "Philosophical fiction",
    description: "An emotionally detached man confronts an absurd world and the judgment of society after a sudden act of violence.",
    image: "https://covers.openlibrary.org/b/isbn/9780679720201-L.jpg",
    price: 9.49,
  },
  {
    id: 40,
    title: "The Plague",
    author: "Albert Camus",
    genre: "Philosophical fiction",
    description: "Residents of a quarantined city respond to an epidemic with fear, solidarity, denial, and a stubborn commitment to human dignity.",
    image: "https://covers.openlibrary.org/b/isbn/9780679720218-L.jpg",
    price: 11.25,
  },
  {
    id: 41,
    title: "Great Expectations",
    author: "Charles Dickens",
    genre: "Classic fiction",
    description: "An orphan receives an unexpected fortune and enters a new social world, learning that wealth cannot resolve every desire or debt.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439563-L.jpg",
    price: 10.5,
  },
  {
    id: 42,
    title: "Oliver Twist",
    author: "Charles Dickens",
    genre: "Classic fiction",
    description: "An orphan escapes a harsh workhouse and encounters criminals, benefactors, and hidden family secrets on the streets of London.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439747-L.jpg",
    price: 9.99,
  },
  {
    id: 43,
    title: "David Copperfield",
    author: "Charles Dickens",
    genre: "Coming-of-age fiction",
    description: "A young boy grows through hardship, friendship, and ambition while searching for a life shaped by his own choices.",
    image: "https://covers.openlibrary.org/b/isbn/9780140439441-L.jpg",
    price: 12.75,
  },
  {
    id: 44,
    title: "The Hunchback of Notre-Dame",
    author: "Victor Hugo",
    genre: "Gothic fiction",
    description: "In medieval Paris, a bell ringer, a dancer, and a conflicted archdeacon become entangled in longing, cruelty, and tragic fate.",
    image: "https://covers.openlibrary.org/b/isbn/9780451527871-L.jpg",
    price: 11.99,
  },
  {
    id: 45,
    title: "The Three Musketeers",
    author: "Alexandre Dumas",
    genre: "Adventure",
    description: "A young swordsman joins three daring companions and becomes caught in a fast-moving world of loyalty, intrigue, and political danger.",
    image: "https://covers.openlibrary.org/b/isbn/9780140440251-L.jpg",
    price: 13.99,
  },
  {
    id: 46,
    title: "Around the World in Eighty Days",
    author: "Jules Verne",
    genre: "Adventure",
    description: "A precise English gentleman wagers that he can circle the globe in eighty days, facing delays and surprises across every continent.",
    image: "https://covers.openlibrary.org/b/isbn/9780140449065-L.jpg",
    price: 9.75,
  },
  {
    id: 47,
    title: "Twenty Thousand Leagues Under the Sea",
    author: "Jules Verne",
    genre: "Science fiction",
    description: "A marine scientist is drawn aboard a remarkable submarine and journeys through hidden oceans under the command of the mysterious Captain Nemo.",
    image: "https://covers.openlibrary.org/b/isbn/9780451530659-L.jpg",
    price: 12.49,
  },
  {
    id: 48,
    title: "Treasure Island",
    author: "Robert Louis Stevenson",
    genre: "Adventure",
    description: "A young boy discovers a pirate map and sails toward buried treasure, encountering mutiny, danger, and the legendary Long John Silver.",
    image: "https://covers.openlibrary.org/b/isbn/9780140367114-L.jpg",
    price: 8.99,
  },
  {
    id: 49,
    title: "Robinson Crusoe",
    author: "Daniel Defoe",
    genre: "Adventure",
    description: "After a shipwreck, a resourceful castaway builds a life on a remote island and learns to survive through patience, ingenuity, and reflection.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439822-L.jpg",
    price: 9.49,
  },
  {
    id: 50,
    title: "Gulliver's Travels",
    author: "Jonathan Swift",
    genre: "Satire",
    description: "A traveler visits extraordinary lands whose strange societies expose the absurdities, vanities, and contradictions of his own culture.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439495-L.jpg",
    price: 10.25,
  },
  {
    id: 51,
    title: "The Time Machine",
    author: "H. G. Wells",
    genre: "Science fiction",
    description: "An inventor travels far into the future and discovers a divided humanity shaped by time, technology, and the consequences of class inequality.",
    image: "https://covers.openlibrary.org/b/isbn/9780451530703-L.jpg",
    price: 8.75,
  },
  {
    id: 52,
    title: "The War of the Worlds",
    author: "H. G. Wells",
    genre: "Science fiction",
    description: "An invasion from Mars throws England into panic as ordinary people struggle to survive against a technologically superior enemy.",
    image: "https://covers.openlibrary.org/b/isbn/9780451528557-L.jpg",
    price: 9.99,
  },
  {
    id: 53,
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian fiction",
    description: "A highly engineered society trades family, privacy, and freedom for stability, forcing one outsider to question the price of happiness.",
    image: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
    price: 12.49,
  },
  {
    id: 54,
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    genre: "Dystopian fiction",
    description: "A fireman whose job is to burn books begins to doubt his society and risks everything to recover curiosity, memory, and independent thought.",
    image: "https://covers.openlibrary.org/b/isbn/9781451678189-L.jpg",
    price: 11.99,
  },
  {
    id: 55,
    title: "Slaughterhouse-Five",
    author: "Kurt Vonnegut",
    genre: "Science fiction",
    description: "A soldier becomes unstuck in time, moving through war, captivity, and ordinary life in a darkly comic meditation on trauma and fate.",
    image: "https://covers.openlibrary.org/b/isbn/9780385333849-L.jpg",
    price: 13.25,
  },
  {
    id: 56,
    title: "Lord of the Flies",
    author: "William Golding",
    genre: "Classic fiction",
    description: "Stranded schoolboys attempt to govern themselves on an island, but fear and rivalry gradually threaten their fragile sense of order.",
    image: "https://covers.openlibrary.org/b/isbn/9780399501487-L.jpg",
    price: 10.99,
  },
  {
    id: 57,
    title: "Animal Farm",
    author: "George Orwell",
    genre: "Political satire",
    description: "Farm animals overthrow their human owner and build a new society, only to discover how power can twist ideals into oppression.",
    image: "https://covers.openlibrary.org/b/isbn/9780451526342-L.jpg",
    price: 8.49,
  },
  {
    id: 58,
    title: "The Road",
    author: "Cormac McCarthy",
    genre: "Post-apocalyptic fiction",
    description: "A father and son travel through a devastated landscape, protecting their bond and searching for signs of goodness in a ruined world.",
    image: "https://covers.openlibrary.org/b/isbn/9780307386458-L.jpg",
    price: 14.75,
  },
  {
    id: 59,
    title: "Beloved",
    author: "Toni Morrison",
    genre: "Historical fiction",
    description: "A formerly enslaved woman is haunted by the past as her family tries to reclaim love, identity, and a future after unimaginable loss.",
    image: "https://covers.openlibrary.org/b/isbn/9781400033416-L.jpg",
    price: 15.49,
  },
  {
    id: 60,
    title: "Invisible Man",
    author: "Ralph Ellison",
    genre: "Literary fiction",
    description: "A young Black man searches for identity and visibility while navigating racism, ideology, and institutions that refuse to see him as an individual.",
    image: "https://covers.openlibrary.org/b/isbn/9780679732761-L.jpg",
    price: 14.99,
  },
  {
    id: 61,
    title: "Their Eyes Were Watching God",
    author: "Zora Neale Hurston",
    genre: "Literary fiction",
    description: "A determined woman travels through love, hardship, and self-discovery while claiming her voice and independence in the American South.",
    image: "https://covers.openlibrary.org/b/isbn/9780061120060-L.jpg",
    price: 12.99,
  },
  {
    id: 62,
    title: "The Color Purple",
    author: "Alice Walker",
    genre: "Historical fiction",
    description: "Letters trace one woman's journey from abuse and silence toward friendship, self-worth, and a powerful new sense of freedom.",
    image: "https://covers.openlibrary.org/b/isbn/9780156028356-L.jpg",
    price: 13.49,
  },
  {
    id: 63,
    title: "The House of the Seven Gables",
    author: "Nathaniel Hawthorne",
    genre: "Gothic fiction",
    description: "A family lives beneath the weight of an old curse, as a decaying house preserves secrets about guilt, greed, and the possibility of renewal.",
    image: "https://covers.openlibrary.org/b/isbn/9780451526823-L.jpg",
    price: 9.99,
  },
  {
    id: 64,
    title: "The Call of Cthulhu",
    author: "H. P. Lovecraft",
    genre: "Cosmic horror",
    description: "Fragments of evidence reveal a terrifying ancient presence and the fragile limits of human understanding when confronted with cosmic forces.",
    image: "https://covers.openlibrary.org/b/isbn/9780486282114-L.jpg",
    price: 8.25,
  },
  {
    id: 65,
    title: "The Wind in the Willows",
    author: "Kenneth Grahame",
    genre: "Children's fiction",
    description: "Four animal friends share riverside adventures while learning about loyalty, home, responsibility, and the consequences of reckless pride.",
    image: "https://covers.openlibrary.org/b/isbn/9780140367620-L.jpg",
    price: 9.49,
  },
  {
    id: 66,
    title: "Peter Pan",
    author: "J. M. Barrie",
    genre: "Children's fantasy",
    description: "Three children fly to Neverland, where pirates, fairies, and lost boys invite them into an adventure between childhood and growing up.",
    image: "https://covers.openlibrary.org/b/isbn/9780141322574-L.jpg",
    price: 8.99,
  },
  {
    id: 67,
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    genre: "Children's fantasy",
    description: "Alice tumbles into a dreamlike world of riddles, strange creatures, and shifting rules that challenge everything she thinks she knows.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439761-L.jpg",
    price: 8.49,
  },
  {
    id: 68,
    title: "The Wonderful Wizard of Oz",
    author: "L. Frank Baum",
    genre: "Children's fantasy",
    description: "After a storm carries her to a magical land, Dorothy follows a road of yellow bricks with three companions who each seek something important.",
    image: "https://covers.openlibrary.org/b/isbn/9780451530710-L.jpg",
    price: 7.99,
  },
  {
    id: 69,
    title: "Heidi",
    author: "Johanna Spyri",
    genre: "Children's fiction",
    description: "A cheerful orphan finds belonging in the Swiss Alps and brings warmth, friendship, and a new sense of hope to the people around her.",
    image: "https://covers.openlibrary.org/b/isbn/9780141322567-L.jpg",
    price: 8.25,
  },
  {
    id: 70,
    title: "Anne of Green Gables",
    author: "L. M. Montgomery",
    genre: "Coming-of-age fiction",
    description: "An imaginative orphan transforms the lives of her new family and neighbors while growing into her ambitions on Prince Edward Island.",
    image: "https://covers.openlibrary.org/b/isbn/9780553213138-L.jpg",
    price: 9.75,
  },
  {
    id: 71,
    title: "A Wrinkle in Time",
    author: "Madeleine L'Engle",
    genre: "Science fiction",
    description: "A young girl travels across space and time with unusual guides to rescue her missing father and confront a force that suppresses individuality.",
    image: "https://covers.openlibrary.org/b/isbn/9780312367541-L.jpg",
    price: 10.49,
  },
  {
    id: 72,
    title: "The Giver",
    author: "Lois Lowry",
    genre: "Dystopian fiction",
    description: "A boy chosen to inherit his community's memories discovers the hidden costs of a society built on sameness and control.",
    image: "https://covers.openlibrary.org/b/isbn/9780544336261-L.jpg",
    price: 9.99,
  },
  {
    id: 73,
    title: "The Golden Compass",
    author: "Philip Pullman",
    genre: "Fantasy",
    description: "A brave girl follows a trail of mysterious kidnappings into frozen lands, where armored bears, parallel worlds, and dangerous secrets await.",
    image: "https://covers.openlibrary.org/b/isbn/9780439954627-L.jpg",
    price: 12.75,
  },
  {
    id: 74,
    title: "The Lion, the Witch and the Wardrobe",
    author: "C. S. Lewis",
    genre: "Fantasy",
    description: "Four siblings enter a magical kingdom through a wardrobe and join a struggle between a noble lion and a ruler who has frozen the land.",
    image: "https://covers.openlibrary.org/b/isbn/9780064404990-L.jpg",
    price: 10.99,
  },
  {
    id: 75,
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    genre: "Fantasy",
    description: "A gifted musician recounts the difficult childhood, education, friendships, and dangers that shaped his legend and his search for answers.",
    image: "https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg",
    price: 15.99,
  },
  {
    id: 76,
    title: "The Princess Bride",
    author: "William Goldman",
    genre: "Fantasy adventure",
    description: "A playful tale of true love, sword fights, daring rescues, and improbable heroes told with equal affection for romance and adventure.",
    image: "https://covers.openlibrary.org/b/isbn/9780156035217-L.jpg",
    price: 12.49,
  },
  {
    id: 77,
    title: "The Martian",
    author: "Andy Weir",
    genre: "Science fiction",
    description: "Stranded alone on Mars, an astronaut uses engineering, humor, and careful planning to stay alive while Earth races to bring him home.",
    image: "https://covers.openlibrary.org/b/isbn/9780804139021-L.jpg",
    price: 14.99,
  },
  {
    id: 78,
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    genre: "Science fiction comedy",
    description: "An ordinary man is swept across the galaxy just before Earth is destroyed, discovering bizarre worlds, improbable companions, and cosmic absurdity.",
    image: "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg",
    price: 11.49,
  },
  {
    id: 79,
    title: "Foundation",
    author: "Isaac Asimov",
    genre: "Science fiction",
    description: "A mathematician predicts the collapse of a vast empire and creates a hidden plan intended to preserve knowledge through centuries of chaos.",
    image: "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg",
    price: 13.99,
  },
  {
    id: 80,
    title: "I, Robot",
    author: "Isaac Asimov",
    genre: "Science fiction",
    description: "A series of connected stories examines the promises, paradoxes, and unintended consequences of building increasingly intelligent robots.",
    image: "https://covers.openlibrary.org/b/isbn/9780553382563-L.jpg",
    price: 10.75,
  },
  {
    id: 81,
    title: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    genre: "Science fiction",
    description: "An envoy visits a distant world whose people challenge his assumptions about gender, loyalty, politics, and what it means to be human.",
    image: "https://covers.openlibrary.org/b/isbn/9780441478125-L.jpg",
    price: 13.49,
  },
  {
    id: 82,
    title: "Dune",
    author: "Frank Herbert",
    genre: "Science fiction",
    description: "A young heir travels to the desert planet Arrakis, where rival houses, scarce resources, and a powerful native culture shape the future of an empire.",
    image: "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
    price: 15.99,
  },
  {
    id: 83,
    title: "The Silmarillion",
    author: "J. R. R. Tolkien",
    genre: "Fantasy",
    description: "A sweeping mythology tells of the creation of Middle-earth, the rise and fall of ancient kingdoms, and the long struggle against a dark power.",
    image: "https://covers.openlibrary.org/b/isbn/9780618391110-L.jpg",
    price: 18.49,
  },
];

export { books };